version: '3.3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes: 
      - .\Prometheus\prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    links:
      - api
  influxdb:
    image: influxdb
    container_name: influxdb
    volumes: 
      - .:/var/lib/influxdb influxdb
    ports:
      - "8086:8086"
    links:
      - api
    environment:
      INFLUXDB_DB: "defaultdb"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "adminpass"
      INFLUXDB_USER: "user"
      INFLUXDB_USER_PASSWORD: "userpass"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
      - prometheus
    volumes:
          - .:/var/lib/grafana
  api:
    image: app-metrics
    container_name: api
    build: 
      context: ./TestAppMetrics/TestAppMetrics
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
