global:
  scrape_interval:     5s 
  evaluation_interval: 5s
  external_labels:
    monitor: 'codelab-monitor'


scrape_configs:
  - job_name: 'prometheus' 
    static_configs:
      - targets: ['localhost:9090']
        labels:
          grupo: 'Prometheus'
  - job_name: Api
    metrics_path: '/metrics-text'
    scrape_interval: 5s
    static_configs:
    - targets: ['api:5000']
      labels:
        grupo: 'Api'


    

